version: "3.3"
services: 
#  mysql-server:
 #   image: mysql:5.7
  #  container_name: mysql-server
   #   environment:  
    #  MYSQL_USER: root  
     # MYSQL_PASSWORD: 123456  
      #MYSQL_ROOT_PASSWORD: 123456
    #volumes: 
     # - D:\data\musql\data:/var/lib/mysql
   # ports: 
    #  - 3306:3306
      
  mysql.db.server:
    image: mysql:5.7
    container_name: mysql.db.server
    environment:
      - LANG=C.UTF-8
      - character-set-server=utf8mb4 
      - collation-server=utf8mb4_unicode_ci
      - MYSQL_ROOT_PASSWORD=123456
    tmpfs:
      - /mysql/tmp/
    volumes:
      - D:\data\musql\data:/var/lib/mysql
    ports:
      - 3306:3306
      